---
- hosts: loadbalancer
  become: true
  tasks:
  - name: verify nginx service
    command: systemctl status nginx

- hosts: webserver
  become: true
  tasks:
  - name: verify apache2 service
    command: systemctl status apache2

- hosts: database
  become: true
  tasks:
  - name: verify mysql service
    command: systemctl status mysql
